// Renders the roadmap steps for the given user into #roadmap-steps-container.
// Steps come from the DATABASE (user.roadmapSteps), generated by Gemini AI for
// whatever goal the user typed.
//
// Each step has:
// 1. A "Mark done" checkbox — real progress tracking, saved to MongoDB,
//    which drives the Dashboard's Roadmap Progress % and Day Streak.
// 2. A click-to-expand panel showing REAL resources for THAT SPECIFIC topic
//    (real YouTube search + AI-curated platforms), not a generic goal-wide search.
// 3. Once marked done, a "Verify this skill" button — AI quiz (70%+ to pass) +
//    a mini-project pick. Only after both does the skill get a Verified badge.

const stepResourceCache = {}; // topic text -> {videos, platforms} — avoids re-calling the API if the same step is opened twice

function renderRoadmap(user){
  const container = document.getElementById('roadmap-steps-container');
  const subheading = document.getElementById('roadmap-goal-sub');
  if (!container) return;

  const goal = user ? user.goal : null;
  const steps = user ? user.roadmapSteps : [];
  const completedSteps = (user && user.completedSteps) ? user.completedSteps : [];
  const verifiedSkills = (user && user.verifiedSkills) ? user.verifiedSkills : [];

  if (!goal || !steps || steps.length === 0){
    container.innerHTML = `<p style="color:var(--ink-soft);font-size:14.5px;">Choose a goal on your Dashboard to get an AI-generated roadmap here.</p>`;
    if (subheading) subheading.textContent = 'Goal: not chosen yet';
    return;
  }

  const doneCount = completedSteps.length;
  if (subheading) subheading.textContent = `Goal: ${goal} · ${doneCount}/${steps.length} steps done · Click a step for resources.`;

  container.innerHTML = steps.map((step, index) => {
    const stepNumber = index + 1;
    const stepId = `step-${index}`;
    const safeStep = step.replace(/"/g, '&quot;');
    const isDone = completedSteps.includes(index);
    const verifiedEntry = verifiedSkills.find(v => v.skillName === step);

    return `
      <div class="roadmap-item">
        <div class="roadmap-row">
          <label class="step-checkbox" style="display:flex;align-items:center;" title="Mark as done">
            <input type="checkbox" class="step-done-checkbox" data-step-index="${index}" ${isDone ? 'checked' : ''} style="width:18px;height:18px;cursor:pointer;">
          </label>
          <div class="rm-dot ${isDone ? 'done' : 'locked'}">${isDone ? '✓' : stepNumber}</div>
          <div class="rm-title roadmap-row-clickable" data-step-id="${stepId}" data-step-topic="${safeStep}" style="cursor:pointer;flex:1;">${step}</div>
          ${isDone ? renderVerifyBadgeOrButton(stepId, safeStep, verifiedEntry) : ''}
          <span class="pill roadmap-row-clickable" data-step-id="${stepId}" data-step-topic="${safeStep}" style="cursor:pointer;">View resources ▾</span>
        </div>
        <div class="step-resources" id="resources-${stepId}" style="display:none;"></div>
        <div class="skill-verify-area" id="verify-${stepId}" style="display:none;padding:4px 4px 16px 42px;"></div>
      </div>
    `;
  }).join('');

  container.querySelectorAll('.roadmap-row-clickable').forEach((el) => {
    el.addEventListener('click', () => toggleStepResources(el));
  });

  container.querySelectorAll('.step-done-checkbox').forEach((checkbox) => {
    checkbox.addEventListener('click', (e) => e.stopPropagation()); // don't trigger the resource panel
    checkbox.addEventListener('change', () => toggleStepDone(checkbox));
  });

  container.querySelectorAll('.verify-skill-btn').forEach((btn) => {
    btn.addEventListener('click', (e) => {
      e.stopPropagation();
      startSkillVerification(btn.dataset.stepId, btn.dataset.skillName);
    });
  });
}

function renderVerifyBadgeOrButton(stepId, skillName, verifiedEntry){
  if (verifiedEntry){
    return `<span class="badge badge-done" style="margin-right:8px;">✓ Verified</span>`;
  }
  return `<button class="pill verify-skill-btn" data-step-id="${stepId}" data-skill-name="${skillName}" style="margin-right:8px;">Verify this skill</button>`;
}

// Marks a step done/undone in the database, then refreshes the dashboard stats + roadmap
async function toggleStepDone(checkbox){
  const stepIndex = parseInt(checkbox.dataset.stepIndex, 10);
  checkbox.disabled = true;

  try {
    const token = localStorage.getItem('skillpilot_token');
    const result = await apiPatch('/auth/toggle-step', { stepIndex }, token);
    localStorage.setItem('skillpilot_user', JSON.stringify(result.user));

    // Refresh everything that depends on progress — dashboard stats + this roadmap view
    if (typeof loadLoggedInUser === 'function') loadLoggedInUser();
  } catch (err) {
    checkbox.checked = !checkbox.checked; // revert the checkbox if the save failed
    alert(err.message || 'Could not save progress — try again.');
  } finally {
    checkbox.disabled = false;
  }
}

async function toggleStepResources(el){
  const stepId = el.dataset.stepId;
  const topic = el.dataset.stepTopic;
  const panel = document.getElementById(`resources-${stepId}`);
  if (!panel) return;

  const alreadyOpen = panel.style.display === 'block';

  // accordion behavior — close any other open panel first
  document.querySelectorAll('.step-resources').forEach((p) => { p.style.display = 'none'; });

  if (alreadyOpen){
    panel.style.display = 'none';
    return;
  }

  panel.style.display = 'block';

  if (stepResourceCache[topic]){
    renderStepResources(panel, stepResourceCache[topic]);
    return;
  }

  panel.innerHTML = `<p style="color:var(--ink-soft);font-size:13.5px;padding:12px 4px;">Finding resources for "${topic}"...</p>`;

  try {
    const token = localStorage.getItem('skillpilot_token');
    const result = await apiGet(`/courses?topic=${encodeURIComponent(topic)}`, token);
    stepResourceCache[topic] = result;
    renderStepResources(panel, result);
  } catch (err) {
    panel.innerHTML = `<p style="color:#D92D20;font-size:13.5px;padding:12px 4px;">${err.message || 'Could not load resources right now.'}</p>`;
  }
}

function renderStepResources(panel, result){
  let html = '';

  if (result.videos && result.videos.length){
    html += result.videos.slice(0, 4).map((v) => `
      <div class="resource-card">
        <div>
          <div class="resource-tag">YouTube</div>
          <div class="resource-title">${v.title}</div>
          <div class="resource-meta">${v.channel}</div>
        </div>
        <a href="${v.url}" target="_blank" class="pill">Watch</a>
      </div>
    `).join('');
  }

  if (result.platforms && result.platforms.length){
    html += result.platforms.map((p) => `
      <div class="resource-card">
        <div>
          <div class="resource-tag">${p.type || ''}</div>
          <div class="resource-title">${p.platform}</div>
          <div class="resource-meta">${p.why || ''}</div>
        </div>
      </div>
    `).join('');
  }

  if (!html){
    html = `<p style="color:var(--ink-soft);font-size:13.5px;padding:12px 4px;">No resources found for this topic yet.</p>`;
  }

  panel.innerHTML = html;
}

/* ================= SKILL VERIFICATION — AI Quiz + Mini-Project ================= */

async function startSkillVerification(stepId, skillName){
  const area = document.getElementById(`verify-${stepId}`);
  if (!area) return;

  area.style.display = 'block';
  area.innerHTML = '<p style="color:var(--ink-soft);font-size:13.5px;">Generating quiz...</p>';

  try {
    const token = localStorage.getItem('skillpilot_token');
    const data = await apiPost('/skill/quiz', { skillName }, token);
    renderQuiz(skillName, data.questions, data.answerKey, area);
  } catch (err) {
    area.innerHTML = `<p style="color:#D92D20;font-size:13.5px;">${err.message || 'Quiz load nahi hua, dobara try karo.'}</p>`;
  }
}

function renderQuiz(skillName, questions, answerKey, area){
  const selected = new Array(questions.length).fill(null);

  area.innerHTML = questions.map((q, qi) => `
    <div style="margin-bottom:14px;">
      <div style="font-weight:600;font-size:14px;margin-bottom:8px;">${qi + 1}. ${q.question}</div>
      ${q.options.map((opt, oi) => `
        <label style="display:block;font-size:13.5px;color:var(--ink-soft);padding:4px 0;cursor:pointer;">
          <input type="radio" name="skv-q${qi}" value="${oi}" style="margin-right:8px;">${opt}
        </label>
      `).join('')}
    </div>
  `).join('') + `<button class="btn-primary skv-submit-quiz" type="button">Submit Quiz</button>
    <div class="skv-quiz-result" style="margin-top:12px;"></div>`;

  area.querySelectorAll('input[type=radio]').forEach(input => {
    input.addEventListener('change', (e) => {
      const qi = parseInt(e.target.name.replace('skv-q', ''), 10);
      selected[qi] = parseInt(e.target.value, 10);
    });
  });

  area.querySelector('.skv-submit-quiz').addEventListener('click', async () => {
    if (selected.includes(null)){
      alert('Sabhi questions answer karo pehle');
      return;
    }
    const resultEl = area.querySelector('.skv-quiz-result');
    resultEl.textContent = 'Checking...';

    try {
      const token = localStorage.getItem('skillpilot_token');
      const data = await apiPost('/skill/verify', { skillName, answers: selected, answerKey }, token);
      renderQuizResult(skillName, data, resultEl);
    } catch (err) {
      resultEl.innerHTML = `<p style="color:#D92D20;">${err.message || 'Kuch galat hua, dobara try karo.'}</p>`;
    }
  });
}

function renderQuizResult(skillName, { score, passed, projectIdeas }, resultEl){
  if (!passed){
    resultEl.innerHTML = `
      <p style="color:var(--warn);font-weight:600;">Score: ${score}% — 70%+ chahiye verify hone ke liye.</p>
      <p style="color:var(--ink-soft);font-size:13.5px;">Thoda revise karo aur dobara try karo.</p>
    `;
    return;
  }

  resultEl.innerHTML = `
    <p style="color:var(--earn);font-weight:600;margin-bottom:10px;">Score: ${score}% — Passed! Ab ek mini-project banao verified badge ke liye:</p>
    ${projectIdeas.map((p) => `
      <div class="card" style="margin-bottom:8px;padding:12px 14px;">
        <div style="font-size:13.5px;">${p}</div>
        <button class="pill skv-pick-project" type="button" data-project="${p.replace(/"/g, '&quot;')}" style="margin-top:8px;">I built this</button>
      </div>
    `).join('')}
  `;

  resultEl.querySelectorAll('.skv-pick-project').forEach(btn => {
    btn.addEventListener('click', async () => {
      const projectChosen = btn.dataset.project;
      btn.disabled = true;
      btn.textContent = 'Saving...';

      try {
        const token = localStorage.getItem('skillpilot_token');
        const data = await apiPost('/skill/complete-project', { skillName, score, projectChosen }, token);
        localStorage.setItem('skillpilot_user', JSON.stringify({ ...JSON.parse(localStorage.getItem('skillpilot_user') || '{}'), verifiedSkills: data.verifiedSkills, careerReadiness: data.careerReadiness }));
        resultEl.innerHTML = '<p style="color:var(--earn);font-weight:700;">✓ Skill Verified! Badge added to your profile.</p>';
        if (typeof loadLoggedInUser === 'function') loadLoggedInUser(); // refresh roadmap + dashboard to show the badge
      } catch (err) {
        btn.disabled = false;
        btn.textContent = 'I built this';
      }
    });
  });
}
