// Renders the roadmap steps for the given user into #roadmap-steps-container.
// Steps come from the DATABASE (user.roadmapSteps), generated by Gemini AI for
// whatever goal the user typed.
//
// Each step has TWO things:
// 1. A "Mark done" checkbox — real progress tracking, saved to MongoDB,
//    which drives the Dashboard's Roadmap Progress % and Day Streak.
// 2. A click-to-expand panel showing REAL resources for THAT SPECIFIC topic
//    (real YouTube search + AI-curated platforms), not a generic goal-wide search.

const stepResourceCache = {}; // topic text -> {videos, platforms} — avoids re-calling the API if the same step is opened twice

function renderRoadmap(user){
  const container = document.getElementById('roadmap-steps-container');
  const subheading = document.getElementById('roadmap-goal-sub');
  if (!container) return;

  const goal = user ? user.goal : null;
  const steps = user ? user.roadmapSteps : [];
  const completedSteps = (user && user.completedSteps) ? user.completedSteps : [];

  if (!goal || !steps || steps.length === 0){
    container.innerHTML = `<p style="color:var(--ink-soft);font-size:14.5px;">Choose a goal on your Dashboard to get an AI-generated roadmap here.</p>`;
    if (subheading) subheading.textContent = 'Goal: not chosen yet';
    return;
  }

  const doneCount = completedSteps.length;
  if (subheading) subheading.textContent = `Goal: ${goal} · ${doneCount}/${steps.length} steps done · Click a step for resources.`;

  container.innerHTML = steps.map((step, index) => {
    const stepNumber = index + 1;
    const stepId = `step-${index}`;
    const safeStep = step.replace(/"/g, '&quot;');
    const isDone = completedSteps.includes(index);

    return `
      <div class="roadmap-item">
        <div class="roadmap-row">
          <label class="step-checkbox" style="display:flex;align-items:center;" title="Mark as done">
            <input type="checkbox" class="step-done-checkbox" data-step-index="${index}" ${isDone ? 'checked' : ''} style="width:18px;height:18px;cursor:pointer;">
          </label>
          <div class="rm-dot ${isDone ? 'done' : 'locked'}">${isDone ? '✓' : stepNumber}</div>
          <div class="rm-title roadmap-row-clickable" data-step-id="${stepId}" data-step-topic="${safeStep}" style="cursor:pointer;flex:1;">${step}</div>
          <span class="pill roadmap-row-clickable" data-step-id="${stepId}" data-step-topic="${safeStep}" style="cursor:pointer;">View resources ▾</span>
        </div>
        <div class="step-resources" id="resources-${stepId}" style="display:none;"></div>
      </div>
    `;
  }).join('');

  container.querySelectorAll('.roadmap-row-clickable').forEach((el) => {
    el.addEventListener('click', () => toggleStepResources(el));
  });

  container.querySelectorAll('.step-done-checkbox').forEach((checkbox) => {
    checkbox.addEventListener('click', (e) => e.stopPropagation()); // don't trigger the resource panel
    checkbox.addEventListener('change', () => toggleStepDone(checkbox));
  });
}

// Marks a step done/undone in the database, then refreshes the dashboard stats + roadmap
async function toggleStepDone(checkbox){
  const stepIndex = parseInt(checkbox.dataset.stepIndex, 10);
  checkbox.disabled = true;

  try {
    const token = localStorage.getItem('skillpilot_token');
    const result = await apiPatch('/auth/toggle-step', { stepIndex }, token);
    localStorage.setItem('skillpilot_user', JSON.stringify(result.user));

    // Refresh everything that depends on progress — dashboard stats + this roadmap view
    if (typeof loadLoggedInUser === 'function') loadLoggedInUser();
  } catch (err) {
    checkbox.checked = !checkbox.checked; // revert the checkbox if the save failed
    alert(err.message || 'Could not save progress — try again.');
  } finally {
    checkbox.disabled = false;
  }
}

async function toggleStepResources(el){
  const stepId = el.dataset.stepId;
  const topic = el.dataset.stepTopic;
  const panel = document.getElementById(`resources-${stepId}`);
  if (!panel) return;

  const alreadyOpen = panel.style.display === 'block';

  // accordion behavior — close any other open panel first
  document.querySelectorAll('.step-resources').forEach((p) => { p.style.display = 'none'; });

  if (alreadyOpen){
    panel.style.display = 'none';
    return;
  }

  panel.style.display = 'block';

  if (stepResourceCache[topic]){
    renderStepResources(panel, stepResourceCache[topic]);
    return;
  }

  panel.innerHTML = `<p style="color:var(--ink-soft);font-size:13.5px;padding:12px 4px;">Finding resources for "${topic}"...</p>`;

  try {
    const token = localStorage.getItem('skillpilot_token');
    const result = await apiGet(`/courses?topic=${encodeURIComponent(topic)}`, token);
    stepResourceCache[topic] = result;
    renderStepResources(panel, result);
  } catch (err) {
    panel.innerHTML = `<p style="color:#D92D20;font-size:13.5px;padding:12px 4px;">${err.message || 'Could not load resources right now.'}</p>`;
  }
}

function renderStepResources(panel, result){
  let html = '';

  if (result.videos && result.videos.length){
    html += result.videos.slice(0, 4).map((v) => `
      <div class="resource-card">
        <div>
          <div class="resource-tag">YouTube</div>
          <div class="resource-title">${v.title}</div>
          <div class="resource-meta">${v.channel}</div>
        </div>
        <a href="${v.url}" target="_blank" class="pill">Watch</a>
      </div>
    `).join('');
  }

  if (result.platforms && result.platforms.length){
    html += result.platforms.map((p) => `
      <div class="resource-card">
        <div>
          <div class="resource-tag">${p.type || ''}</div>
          <div class="resource-title">${p.platform}</div>
          <div class="resource-meta">${p.why || ''}</div>
        </div>
      </div>
    `).join('');
  }

  if (!html){
    html = `<p style="color:var(--ink-soft);font-size:13.5px;padding:12px 4px;">No resources found for this topic yet.</p>`;
  }

  panel.innerHTML = html;
}
